### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion-manual#1]
Running `make clean && make` gives me:

```
! Package Listings Error: File `"Examples/Partitions/pre_image/preimage(.cc")' 
not found.
```

**Comment by alexaiken** [comment]
I added the missing files to the repository --- should be fixed.
________________________________
From: Elliott Slaughter ***@***.***>
Sent: Thursday, September 8, 2022 11:57 AM
To: StanfordLegion/legion-manual ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StanfordLegion/legion-manual] Build failure (Issue #1)


Running make clean && make gives me:

! Package Listings Error: File `"Examples/Partitions/pre_image/preimage(.cc")'
not found.
